services:
  postgres:
    image: postgres:17-alpine
    container_name: shibary-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shibary
      POSTGRES_USER: shibary
      POSTGRES_PASSWORD: shibary
    volumes:
      - pgdata:/var/lib/postgresql/data

  shibary-back:
    build: .
    container_name: shibary-back
    restart: unless-stopped
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shibary
      DB_USERNAME: shibary
      DB_PASSWORD: shibary
      CHAD_API_KEY: ${CHAD_API_KEY}

volumes:
  pgdata:
