services:
  postgres:
    image: postgres:17-alpine
    container_name: shibary-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shibary
      POSTGRES_USER: shibary
      POSTGRES_PASSWORD: shibary
    volumes:
      - pgdata:/var/lib/postgresql/data

  shibary-back:
    build: .
    container_name: shibary-back
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shibary
      DB_USERNAME: shibary
      DB_PASSWORD: shibary
      CHAD_API_KEY: chad-521f2bbdce924f3099b5d7b9b87aeec2tixjo1r1

volumes:
  pgdata:
