spring:
  application:
    name: shibary_back
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://host.docker.internal:11434}
      chat:
        model: qwen2.5:0.5b
        options:
          num-predict: 80
          num-ctx: 256
          temperature: 0.2
          top-k: 10
          top-p: 0.5
          num-thread: 4
